# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True, verbose_name='\u51fa\u5382\u65e5\u671f')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u5b57')),
                ('speed', models.IntegerField(default=300, verbose_name='\u65f6\u901f')),
                ('last_update', models.DateField(auto_now=True)),
                ('is_used', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5728\u7528')),
            ],
            options={
                'db_table': 'huocart',
                'verbose_name': '\u706b\u8f66\u7c7b',
            },
        ),
    ]
