# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t02', '0002_auto_20180814_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firecart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u51fa\u5382\u65e5\u671f'),
        ),
    ]
